from __future__ import annotations

from pathlib import Path
from typing import Any

from app.schemas import ArchitectureModel, Component


SUPPORTED_DATABASES = {
    "postgresql": "postgresql",
    "postgres": "postgresql",
    "mysql": "mysql",
    "mongodb": "mongodb",
    "mongo": "mongodb",
    "sqlite": "sqlite",
}


DATABASE_GENERATION_CAPABILITIES = [
    {
        "catalog_id": "relational-database",
        "kind": "component",
        "generator": "database",
        "supported": True,
        "phase": "implemented",
        "reason": (
            "PostgreSQL, MySQL, and SQLite initialization files "
            "can be generated."
        ),
        "technologies": [
            "PostgreSQL",
            "MySQL",
            "SQLite",
        ],
        "generated_files": [
            "database/init.sql",
        ],
    },
    {
        "catalog_id": "document-database",
        "kind": "component",
        "generator": "database",
        "supported": True,
        "phase": "implemented",
        "reason": (
            "MongoDB initialization files can be generated."
        ),
        "technologies": [
            "MongoDB",
        ],
        "generated_files": [
            "database/init.js",
        ],
    },
    {
        "catalog_id": "database-access",
        "kind": "connection",
        "generator": "database",
        "supported": False,
        "phase": "represented",
        "reason": (
            "Database connections remain in architecture.json, but "
            "application data-access code is not generated yet."
        ),
        "technologies": [
            "PostgreSQL",
            "MySQL",
            "MongoDB",
            "SQLite",
        ],
        "generated_files": [],
    },
]


def _normalize_text(value: object) -> str:
    return str(value or "").strip().lower()


def _component_search_text(
    component: Component,
) -> str:
    values = [
        component.id,
        component.name,
        component.type,
        component.technology,
        component.description,
    ]

    metadata = getattr(
        component,
        "metadata",
        None,
    )

    if isinstance(metadata, dict):
        values.extend(
            [
                metadata.get("technology"),
                metadata.get("database"),
                metadata.get("provider"),
                metadata.get("engine"),
                metadata.get("runtime"),
            ]
        )

    return " ".join(
        str(value)
        for value in values
        if value
    ).lower()


def is_database_component(
    component: Component,
) -> bool:
    if _normalize_text(component.type) == "database":
        return True

    search_text = _component_search_text(
        component,
    )

    return any(
        technology in search_text
        for technology in SUPPORTED_DATABASES
    )


def detect_database_engine(
    component: Component,
) -> str | None:
    search_text = _component_search_text(
        component,
    )

    detection_order = [
        ("postgresql", "postgresql"),
        ("postgres", "postgresql"),
        ("mongodb", "mongodb"),
        ("mongo", "mongodb"),
        ("mysql", "mysql"),
        ("sqlite", "sqlite"),
    ]

    for token, engine in detection_order:
        if token in search_text:
            return engine

    return None


def find_supported_database(
    model: ArchitectureModel,
) -> tuple[Component | None, str | None]:
    """
    Return the first supported database component.

    SCRUM-67 generates configuration for one database service.
    Additional database components remain in architecture.json but are
    reported as skipped.
    """

    for component in model.components:
        if not is_database_component(
            component,
        ):
            continue

        engine = detect_database_engine(
            component,
        )

        if engine:
            return component, engine

    return None, None


def get_skipped_database_components(
    model: ArchitectureModel,
    generated_component_id: str | None = None,
) -> list[str]:
    skipped: list[str] = []

    for component in model.components:
        if not is_database_component(
            component,
        ):
            continue

        if (
            generated_component_id is not None
            and component.id == generated_component_id
        ):
            continue

        skipped.append(component.name)

    return skipped


def _postgresql_init_content(
    project_name: str,
) -> str:
    return f"""-- Generated by ArchVision AI
-- Project: {project_name}
-- Database: PostgreSQL

CREATE TABLE IF NOT EXISTS app_health (
    id SERIAL PRIMARY KEY,
    status VARCHAR(50) NOT NULL DEFAULT 'healthy',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_health (status)
VALUES ('healthy');
"""


def _mysql_init_content(
    project_name: str,
) -> str:
    return f"""-- Generated by ArchVision AI
-- Project: {project_name}
-- Database: MySQL

CREATE TABLE IF NOT EXISTS app_health (
    id INT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(50) NOT NULL DEFAULT 'healthy',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_health (status)
VALUES ('healthy');
"""


def _mongodb_init_content(
    project_name: str,
) -> str:
    return f"""// Generated by ArchVision AI
// Project: {project_name}
// Database: MongoDB

db = db.getSiblingDB(
  process.env.MONGO_INITDB_DATABASE || "app_db"
);

db.createCollection("app_health");

db.app_health.insertOne({{
  status: "healthy",
  createdAt: new Date()
}});
"""


def _sqlite_init_content(
    project_name: str,
) -> str:
    return f"""-- Generated by ArchVision AI
-- Project: {project_name}
-- Database: SQLite

CREATE TABLE IF NOT EXISTS app_health (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    status TEXT NOT NULL DEFAULT 'healthy',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_health (status)
VALUES ('healthy');
"""


def _get_init_file_details(
    engine: str,
    project_name: str,
) -> tuple[str, str]:
    if engine == "postgresql":
        return (
            "init.sql",
            _postgresql_init_content(
                project_name,
            ),
        )

    if engine == "mysql":
        return (
            "init.sql",
            _mysql_init_content(
                project_name,
            ),
        )

    if engine == "mongodb":
        return (
            "init.js",
            _mongodb_init_content(
                project_name,
            ),
        )

    if engine == "sqlite":
        return (
            "init.sql",
            _sqlite_init_content(
                project_name,
            ),
        )

    raise ValueError(
        f"Unsupported database engine: {engine}"
    )


def generate_database_files(
    project_dir: Path,
    model: ArchitectureModel,
) -> dict[str, Any]:
    """
    Generate a simple initialization file for one supported database.

    Supported database engines:

    - PostgreSQL
    - MySQL
    - MongoDB
    - SQLite
    """

    component, engine = find_supported_database(
        model,
    )

    if component is None or engine is None:
        return {
            "database_engine": None,
            "generated_database_component_id": None,
            "generated_database_files": [],
            "skipped_database_components": (
                get_skipped_database_components(
                    model,
                )
            ),
        }

    database_dir = (
        Path(project_dir)
        / "database"
    )

    database_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    filename, content = (
        _get_init_file_details(
            engine,
            model.name,
        )
    )

    init_file = (
        database_dir
        / filename
    )

    init_file.write_text(
        content,
        encoding="utf-8",
    )

    return {
        "database_engine": engine,
        "generated_database_component_id": component.id,
        "generated_database_files": [
            str(
                init_file.relative_to(
                    project_dir,
                )
            )
        ],
        "skipped_database_components": (
            get_skipped_database_components(
                model,
                generated_component_id=component.id,
            )
        ),
    }